//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlingerSystem.Employee.Domain.Message {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ListEmployeeMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ListEmployeeMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KlingerSystem.Employee.Domain.Message.ListEmployeeMessages", typeof(ListEmployeeMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anotação inválida inserida, não permitido nulo ou vazio..
        /// </summary>
        public static string ANNOTATION_REPIT_ERRO_MSG {
            get {
                return ResourceManager.GetString("ANNOTATION_REPIT_ERRO_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nascimento inválido..
        /// </summary>
        public static string BIRTHDATE_ERRO_MSG {
            get {
                return ResourceManager.GetString("BIRTHDATE_ERRO_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comissão não pode ser menor que 0..
        /// </summary>
        public static string COMMISSION_ERRO_MSG {
            get {
                return ResourceManager.GetString("COMMISSION_ERRO_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cpf não pode ser alterado..
        /// </summary>
        public static string CPF_ALTERACAO_ERRO_MSG {
            get {
                return ResourceManager.GetString("CPF_ALTERACAO_ERRO_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome completo inválido.
        /// </summary>
        public static string FULLNAME_ERRO_MSG {
            get {
                return ResourceManager.GetString("FULLNAME_ERRO_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caminho do arquivo inválido..
        /// </summary>
        public static string IMAGEPATH_ERRO_MSG {
            get {
                return ResourceManager.GetString("IMAGEPATH_ERRO_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número já adicionado..
        /// </summary>
        public static string NUMBER_REPIT_ERRO_MSG {
            get {
                return ResourceManager.GetString("NUMBER_REPIT_ERRO_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máximo de telefones permitidos são 3..
        /// </summary>
        public static string PHONE_COUNT_MAX_ERRO_MSG {
            get {
                return ResourceManager.GetString("PHONE_COUNT_MAX_ERRO_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rg não pode ser alterado..
        /// </summary>
        public static string RG_ALTERACAO_ERRO_MSG {
            get {
                return ResourceManager.GetString("RG_ALTERACAO_ERRO_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Sexo inválido..
        /// </summary>
        public static string TYPOSEXO_ERRO_MSG {
            get {
                return ResourceManager.GetString("TYPOSEXO_ERRO_MSG", resourceCulture);
            }
        }
    }
}
