//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlingerSystem.Business.Domain.Message {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ListCompanyMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ListCompanyMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KlingerSystem.Business.Domain.Message.ListCompanyMessages", typeof(ListCompanyMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Campo Razão Social deve conter entre 5 e 500 caracteres..
        /// </summary>
        public static string CompanyNameText_Erro {
            get {
                return ResourceManager.GetString("CompanyNameText_Erro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Nome Fantasia deve conter entre 5 e 255 caracteres..
        /// </summary>
        public static string FantasyNameText_Erro {
            get {
                return ResourceManager.GetString("FantasyNameText_Erro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa do tipo Juridico, não pode ser incluso um cpf..
        /// </summary>
        public static string JURIDICO_CPF_ERRO {
            get {
                return ResourceManager.GetString("JURIDICO_CPF_ERRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matriz id inválido..
        /// </summary>
        public static string MatrizId_Erro {
            get {
                return ResourceManager.GetString("MatrizId_Erro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Inscrição Municipal deve conter entre 5 e 20 caracteres..
        /// </summary>
        public static string MunicipalRegistrationText_Erro {
            get {
                return ResourceManager.GetString("MunicipalRegistrationText_Erro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número já adicionado..
        /// </summary>
        public static string NUMBER_REPIT_ERRO_MSG {
            get {
                return ResourceManager.GetString("NUMBER_REPIT_ERRO_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Pessoa inválido..
        /// </summary>
        public static string PERSONTYPE_ERRO {
            get {
                return ResourceManager.GetString("PERSONTYPE_ERRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa do tipo Físical, não pode ser inclusa um cnpj.
        /// </summary>
        public static string PHISYCAL_CNPJ_ERRO {
            get {
                return ResourceManager.GetString("PHISYCAL_CNPJ_ERRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máximo de telefones permitidos, são 2..
        /// </summary>
        public static string PHONE_COUNT_MAX_ERRO_MSG {
            get {
                return ResourceManager.GetString("PHONE_COUNT_MAX_ERRO_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa do tipo Físical, não pode incluir Razão Social..
        /// </summary>
        public static string PHYSICAL_COMPANYNAME_ERRO {
            get {
                return ResourceManager.GetString("PHYSICAL_COMPANYNAME_ERRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa do tipo Físical, não pode incluir Nome Fantasia..
        /// </summary>
        public static string PHYSICAL_FANTASYNAME_ERRO {
            get {
                return ResourceManager.GetString("PHYSICAL_FANTASYNAME_ERRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa do tipo Física, não pode incluir Incrição Municipal.
        /// </summary>
        public static string PHYSICAL_MUNICIPALREGISTRATION_ERRO {
            get {
                return ResourceManager.GetString("PHYSICAL_MUNICIPALREGISTRATION_ERRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa do tipo Física, não pode incluir Incrição Estadual..
        /// </summary>
        public static string PHYSICAL_STATEREGISTRATION_ERRO {
            get {
                return ResourceManager.GetString("PHYSICAL_STATEREGISTRATION_ERRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Inscrição Estadual deve conter 14 caracteres..
        /// </summary>
        public static string StateRegistrationText_Erro {
            get {
                return ResourceManager.GetString("StateRegistrationText_Erro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regime Especial Tributário inválido..
        /// </summary>
        public static string TAXESPECIALREGIME_ERRO {
            get {
                return ResourceManager.GetString("TAXESPECIALREGIME_ERRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regime tributário inválido..
        /// </summary>
        public static string TAXREGIME_ERRO {
            get {
                return ResourceManager.GetString("TAXREGIME_ERRO", resourceCulture);
            }
        }
    }
}
