// <auto-generated />
using System;
using KlingerSystem.Business.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KlingerSystem.Business.Infrastructure.Migrations
{
    [DbContext(typeof(BusinessContext))]
    [Migration("20211027184939_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KlingerSystem.Business.Domain.Models.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Complement")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Neighborhood")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Reference")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("char(2)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("varchar(8)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .IsUnique();

                    b.ToTable("TB_Address");
                });

            modelBuilder.Entity("KlingerSystem.Business.Domain.Models.Cnae", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Devision")
                        .IsRequired()
                        .HasColumnType("varchar(7)");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TB_Cnae");
                });

            modelBuilder.Entity("KlingerSystem.Business.Domain.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CnaeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("CompanyType")
                        .HasColumnType("int");

                    b.Property<string>("FantasyName")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("MatrizId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MunicipalRegistration")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("PersonType")
                        .HasColumnType("int");

                    b.Property<string>("Site")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("SpecialTaxRegime")
                        .HasColumnType("int");

                    b.Property<string>("StateRegistration")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("TaxRegime")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CnaeId");

                    b.HasIndex("MatrizId");

                    b.ToTable("TB_Company");
                });

            modelBuilder.Entity("KlingerSystem.Business.Domain.Models.Email", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddressEmail")
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .IsUnique();

                    b.ToTable("TB_Email");
                });

            modelBuilder.Entity("KlingerSystem.Business.Domain.Models.Phone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ddd")
                        .IsRequired()
                        .HasColumnType("char(2)");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("varchar(9)");

                    b.Property<int>("PhoneType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("TB_Phone");
                });

            modelBuilder.Entity("KlingerSystem.Business.Domain.Models.Address", b =>
                {
                    b.HasOne("KlingerSystem.Business.Domain.Models.Company", "Company")
                        .WithOne("Address")
                        .HasForeignKey("KlingerSystem.Business.Domain.Models.Address", "CompanyId")
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("KlingerSystem.Business.Domain.Models.Company", b =>
                {
                    b.HasOne("KlingerSystem.Business.Domain.Models.Cnae", "Cnae")
                        .WithMany("Companies")
                        .HasForeignKey("CnaeId")
                        .IsRequired();

                    b.HasOne("KlingerSystem.Business.Domain.Models.Company", "Matriz")
                        .WithMany()
                        .HasForeignKey("MatrizId");

                    b.OwnsOne("KlingerSystem.Core.DomainObjects.Cnpj", "Cnpj", b1 =>
                        {
                            b1.Property<Guid>("CompanyId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Number")
                                .HasMaxLength(14)
                                .HasColumnType("varchar(14)")
                                .HasColumnName("Cnpj");

                            b1.HasKey("CompanyId");

                            b1.ToTable("TB_Company");

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.OwnsOne("KlingerSystem.Core.DomainObjects.Cpf", "Cpf", b1 =>
                        {
                            b1.Property<Guid>("CompanyId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Number")
                                .HasMaxLength(11)
                                .HasColumnType("varchar(11)")
                                .HasColumnName("Cpf");

                            b1.HasKey("CompanyId");

                            b1.ToTable("TB_Company");

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.Navigation("Cnae");

                    b.Navigation("Cnpj");

                    b.Navigation("Cpf");

                    b.Navigation("Matriz");
                });

            modelBuilder.Entity("KlingerSystem.Business.Domain.Models.Email", b =>
                {
                    b.HasOne("KlingerSystem.Business.Domain.Models.Company", "Company")
                        .WithOne("Email")
                        .HasForeignKey("KlingerSystem.Business.Domain.Models.Email", "CompanyId")
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("KlingerSystem.Business.Domain.Models.Phone", b =>
                {
                    b.HasOne("KlingerSystem.Business.Domain.Models.Company", "Company")
                        .WithMany("Phones")
                        .HasForeignKey("CompanyId")
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("KlingerSystem.Business.Domain.Models.Cnae", b =>
                {
                    b.Navigation("Companies");
                });

            modelBuilder.Entity("KlingerSystem.Business.Domain.Models.Company", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("Email");

                    b.Navigation("Phones");
                });
#pragma warning restore 612, 618
        }
    }
}
