//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlingerSystem.Employee.Api.Application.Commands.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommandMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommandMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KlingerSystem.Employee.Api.Application.Commands.Messages.CommandMessages", typeof(CommandMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade inválida..
        /// </summary>
        public static string AddressCity_Invalido {
            get {
                return ResourceManager.GetString("AddressCity_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Cidade precisa ter  entre 2 e 100 caracteres..
        /// </summary>
        public static string AddressCityText_Invalido {
            get {
                return ResourceManager.GetString("AddressCityText_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo complemento está inválido..
        /// </summary>
        public static string AddressComplement_Invalido {
            get {
                return ResourceManager.GetString("AddressComplement_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bairro inválida..
        /// </summary>
        public static string AddressNeighborhood_Invalido {
            get {
                return ResourceManager.GetString("AddressNeighborhood_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Bairro precisa ter entre 2 e 100 caracteres..
        /// </summary>
        public static string AddressNeighborhoodText_Invalido {
            get {
                return ResourceManager.GetString("AddressNeighborhoodText_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número inválido..
        /// </summary>
        public static string AddressNumber_Invalido {
            get {
                return ResourceManager.GetString("AddressNumber_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo número precisa ter entre 1 e 20 caracteres..
        /// </summary>
        public static string AddressNumberText_Invalido {
            get {
                return ResourceManager.GetString("AddressNumberText_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo referencia está inválido..
        /// </summary>
        public static string AddressReference_Invalido {
            get {
                return ResourceManager.GetString("AddressReference_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado inválido..
        /// </summary>
        public static string AddressState_Invalido {
            get {
                return ResourceManager.GetString("AddressState_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Estado precisa ter 2 caracteres.
        /// </summary>
        public static string AddressStateText_Invalido {
            get {
                return ResourceManager.GetString("AddressStateText_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logradouro inválido..
        /// </summary>
        public static string AddressStreet_Invalido {
            get {
                return ResourceManager.GetString("AddressStreet_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Logradouro precisa ter entre 2 e 100 caracteres..
        /// </summary>
        public static string AddressStreetText_Invalido {
            get {
                return ResourceManager.GetString("AddressStreetText_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cep inválido..
        /// </summary>
        public static string AddressZipCode_Invalido {
            get {
                return ResourceManager.GetString("AddressZipCode_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Cep precisa ter 8 caracteres.
        /// </summary>
        public static string AddressZipCodeText_Invalido {
            get {
                return ResourceManager.GetString("AddressZipCodeText_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anotações do funcionário inválido..
        /// </summary>
        public static string Annotation_Invalido {
            get {
                return ResourceManager.GetString("Annotation_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de nascimento inválida..
        /// </summary>
        public static string BirthDate_Invalido {
            get {
                return ResourceManager.GetString("BirthDate_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id do Comercio inválido..
        /// </summary>
        public static string BusinessId_Invalido {
            get {
                return ResourceManager.GetString("BusinessId_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comissão inválida fornecedida, valor deve ser entre 1 e 100..
        /// </summary>
        public static string Commission_Invalido {
            get {
                return ResourceManager.GetString("Commission_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cpf inválido..
        /// </summary>
        public static string Cpf_Invalido {
            get {
                return ResourceManager.GetString("Cpf_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail inválido..
        /// </summary>
        public static string Email_Invalido {
            get {
                return ResourceManager.GetString("Email_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id do Funcionário inválido..
        /// </summary>
        public static string EmployeeId_Invalido {
            get {
                return ResourceManager.GetString("EmployeeId_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cpf já cadastrado..
        /// </summary>
        public static string Erro_CpfJaCadastrado {
            get {
                return ResourceManager.GetString("Erro_CpfJaCadastrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail já cadastrado..
        /// </summary>
        public static string Erro_EmailJaCadastrado {
            get {
                return ResourceManager.GetString("Erro_EmailJaCadastrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha ao registrar funcionario..
        /// </summary>
        public static string Erro_FalhaAoRegistrarFuncionario {
            get {
                return ResourceManager.GetString("Erro_FalhaAoRegistrarFuncionario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome Completo inválido..
        /// </summary>
        public static string FullName_Invalido {
            get {
                return ResourceManager.GetString("FullName_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagem inválida fornecida..
        /// </summary>
        public static string ImagePath_Invalido {
            get {
                return ResourceManager.GetString("ImagePath_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ddd inválido..
        /// </summary>
        public static string PhoneDdd_Invalido {
            get {
                return ResourceManager.GetString("PhoneDdd_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ddd deve conter 2 caracteres..
        /// </summary>
        public static string PhoneDddText_Invalido {
            get {
                return ResourceManager.GetString("PhoneDddText_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone residencial inválido..
        /// </summary>
        public static string PhoneHome_Invalido {
            get {
                return ResourceManager.GetString("PhoneHome_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone residencial deve conter 8 caracteres..
        /// </summary>
        public static string PhoneHomeText_Invalido {
            get {
                return ResourceManager.GetString("PhoneHomeText_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máximo de telefones permitidos são 3..
        /// </summary>
        public static string PhoneQtdeMax {
            get {
                return ResourceManager.GetString("PhoneQtdeMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celular inválido..
        /// </summary>
        public static string PhoneSmartPhone_Invalido {
            get {
                return ResourceManager.GetString("PhoneSmartPhone_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celular deve conter 9 caracteres..
        /// </summary>
        public static string PhoneSmartPhoneTest_Invalido {
            get {
                return ResourceManager.GetString("PhoneSmartPhoneTest_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone comercial inválido informado..
        /// </summary>
        public static string PhoneWorkstation_Invalido {
            get {
                return ResourceManager.GetString("PhoneWorkstation_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone comercial deve conter entre 8 ou 9 caracteres..
        /// </summary>
        public static string PhoneWorkstationText_Invalido {
            get {
                return ResourceManager.GetString("PhoneWorkstationText_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de expedição do Rg inválida..
        /// </summary>
        public static string RgExpeditionDate_invalido {
            get {
                return ResourceManager.GetString("RgExpeditionDate_invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Órgão emissor do Rg inválida..
        /// </summary>
        public static string RgIssuere_Invalido {
            get {
                return ResourceManager.GetString("RgIssuere_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Rg inválido..
        /// </summary>
        public static string RgNumber_Invalido {
            get {
                return ResourceManager.GetString("RgNumber_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Sexo inválido..
        /// </summary>
        public static string TypeSexo_Invalido {
            get {
                return ResourceManager.GetString("TypeSexo_Invalido", resourceCulture);
            }
        }
    }
}
